export {default as Accueil} from './Accueil'
export {default as AdminDashboard } from './AdminDashboard'
export {default as Login} from './Login'
export {default as Boutique} from './Boutique'
export {default as Clientdashboard} from './Clientdashboard'
export {default as Contact} from './Contact'
export {default as Singup} from './Singup'
export {default as Notfound} from './Notfound'
export {default as Resetpassword} from './ResetPassword'
export {default as VendorDashboard} from './VendorDashboard'
export {default as VerificationEmail} from './VerificationEmail'
export {default as Devenirvendeur} from './Devenirvendeur'